#!/bin/sh
# Rebuilds the trimmed three.js that world.js imports, with exactly the THREE.*
# names world.js uses. Run it whenever world.js starts using a new THREE.*
# class; a missing one fails loudly at boot ("THREE.X is not a constructor").
# The output name carries a content hash (vendor/three-av.<hash>.min.js) so it
# can be cached for a year; world.js and the pages are pointed at it.
# Needs Bun (https://bun.sh) and Node.
set -e
cd "$(dirname "$0")/.."
names=$(grep -o 'THREE\.[A-Za-z0-9_]*' world.js | sed 's/THREE\.//' | sort -u | paste -sd, - | sed 's/,/, /g')
cat > tools/three-entry.js <<ENTRY
// Generated by tools/build-three.sh from the THREE.* names world.js uses.
export { $names } from "./three/three.module.min.js";
export { EffectComposer } from "./three/pp/EffectComposer.js";
export { RenderPass } from "./three/pp/RenderPass.js";
export { UnrealBloomPass } from "./three/pp/UnrealBloomPass.js";
export { OutputPass } from "./three/pp/OutputPass.js";
ENTRY
bun build tools/three-entry.js --minify --format=esm --outfile=tools/three-av.tmp.js
hash=$(shasum -a 256 tools/three-av.tmp.js | cut -c1-10)
rm -f vendor/three-av*.js
mv tools/three-av.tmp.js "vendor/three-av.$hash.min.js"
perl -pi -e "s#vendor/three-av(\.[0-9a-f]+)?\.min\.js#vendor/three-av.$hash.min.js#g" world.js index.html
node tools/sync-pages.mjs > /dev/null
echo "vendor/three-av.$hash.min.js"
